# Generated by Django 5.1.3 on 2024-12-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emial_token',
            new_name='email_token',
        ),
    ]
