# Generated by Django 5.1.3 on 2024-12-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
