# Generated by Django 5.1.3 on 2024-12-03 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('color_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SizeVariation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('size_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color_variation',
            field=models.ManyToManyField(to='siteApp.colorvariation'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_variation',
            field=models.ManyToManyField(to='siteApp.sizevariation'),
        ),
    ]
