# Generated by Django 5.1.3 on 2024-12-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0003_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variation',
        ),
        migrations.DeleteModel(
            name='ColorVariation',
        ),
        migrations.DeleteModel(
            name='SizeVariation',
        ),
    ]
